from pathlib import Path
p=Path('src/jauas_main.cpp')
s=p.read_text(encoding='utf-8')
old='''        if(starts(line,"add ")||starts(line,"sub ")||starts(line,"or ")||starts(line,"cmp ")||starts(line,"test ")){\n            auto sp=line.find(' ');std::string op=line.substr(0,sp);auto [dst,src]=operands(line,sp+1);\n            int dr=im.x64?reg64(dst):reg32(dst),sr=im.x64?reg64(src):reg32(src);\n            if(dr<0)throw std::runtime_error("unsupported "+op+" destination: "+dst);\n            if(sr>=0){\n                uint8_t opc=op=="add"?0x01:op=="sub"?0x29:op=="or"?0x09:op=="cmp"?0x39:0x85;\n                if(im.x64)rex(o,true,sr,0,dr);o.push_back(opc);o.push_back(modrm(3,sr,dr));continue;\n            }'''
new='''        if(starts(line,"add ")||starts(line,"sub ")||starts(line,"and ")||starts(line,"or ")||starts(line,"xor ")||starts(line,"cmp ")||starts(line,"test ")){\n            auto sp=line.find(' ');std::string op=line.substr(0,sp);auto [dst,src]=operands(line,sp+1);\n            int dr=im.x64?reg64(dst):reg32(dst),sr=im.x64?reg64(src):reg32(src);\n            if(dr<0)throw std::runtime_error("unsupported "+op+" destination: "+dst);\n            if(sr>=0){\n                uint8_t opc=op=="add"?0x01:op=="sub"?0x29:op=="and"?0x21:op=="or"?0x09:op=="xor"?0x31:op=="cmp"?0x39:0x85;\n                if(im.x64)rex(o,true,sr,0,dr);o.push_back(opc);o.push_back(modrm(3,sr,dr));continue;\n            }'''
if old not in s: raise SystemExit('jauas binary opcode anchor missing')
s=s.replace(old,new,1)
old2='''        if(starts(line,"neg ")){\n            std::string r=trim(line.substr(4));int rr=im.x64?reg64(r):reg32(r);if(rr<0)throw std::runtime_error("unsupported neg");\n            if(im.x64)rex(o,true,3,0,rr);o.push_back(0xf7);o.push_back(modrm(3,3,rr));continue;\n        }\n        if(line=="and al,cl"||line=="and al, cl"){o.insert(o.end(),{0x20,0xc8});continue;}\n        if(line=="xor eax,eax"||line=="xor eax, eax"){o.insert(o.end(),{0x31,0xc0});continue;}'''
new2='''        if(starts(line,"neg ")){\n            std::string r=trim(line.substr(4));int rr=im.x64?reg64(r):reg32(r);if(rr<0)throw std::runtime_error("unsupported neg");\n            if(im.x64)rex(o,true,3,0,rr);o.push_back(0xf7);o.push_back(modrm(3,3,rr));continue;\n        }\n        if(starts(line,"not ")){\n            std::string r=trim(line.substr(4));int rr=im.x64?reg64(r):reg32(r);if(rr<0)throw std::runtime_error("unsupported not");\n            if(im.x64)rex(o,true,2,0,rr);o.push_back(0xf7);o.push_back(modrm(3,2,rr));continue;\n        }\n        if(starts(line,"shl ")||starts(line,"sar ")){\n            auto sp=line.find(' ');std::string op=line.substr(0,sp);auto [dst,src]=operands(line,sp+1);int rr=im.x64?reg64(dst):reg32(dst);if(rr<0||src!="cl")throw std::runtime_error("unsupported "+op+": "+line);int ext=op=="shl"?4:7;if(im.x64)rex(o,true,0,0,rr);o.push_back(0xd3);o.push_back(modrm(3,ext,rr));continue;\n        }\n        if(line=="and al,cl"||line=="and al, cl"){o.insert(o.end(),{0x20,0xc8});continue;}\n        if(line=="xor eax,eax"||line=="xor eax, eax"){o.insert(o.end(),{0x31,0xc0});continue;}'''
if old2 not in s: raise SystemExit('jauas unary/shift anchor missing')
s=s.replace(old2,new2,1)
p.write_text(s,encoding='utf-8')
