#include <algorithm>
#include <cctype>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

namespace fs = std::filesystem;

static uint16_t r16(const std::vector<uint8_t>& b, size_t p){ if(p+2>b.size()) throw std::runtime_error("truncated input"); return (uint16_t)(b[p]|(b[p+1]<<8)); }
static uint32_t r32(const std::vector<uint8_t>& b, size_t p){ if(p+4>b.size()) throw std::runtime_error("truncated input"); return (uint32_t)b[p]|((uint32_t)b[p+1]<<8)|((uint32_t)b[p+2]<<16)|((uint32_t)b[p+3]<<24); }
static uint64_t r64(const std::vector<uint8_t>& b, size_t p){ uint64_t v=0; for(int i=0;i<8;++i)v|=(uint64_t)b.at(p+i)<<(8*i); return v; }
static void w16(std::vector<uint8_t>& b,uint16_t v){ b.push_back((uint8_t)v); b.push_back((uint8_t)(v>>8)); }
static void p16(std::vector<uint8_t>& b,size_t p,uint16_t v){ if(p+2>b.size())throw std::runtime_error("patch overflow");b[p]=(uint8_t)v;b[p+1]=(uint8_t)(v>>8); }
static void p32(std::vector<uint8_t>& b,size_t p,uint32_t v){ if(p+4>b.size())throw std::runtime_error("patch overflow");for(int i=0;i<4;++i)b[p+i]=(uint8_t)(v>>(8*i)); }
static void p64(std::vector<uint8_t>& b,size_t p,uint64_t v){ if(p+8>b.size())throw std::runtime_error("patch overflow");for(int i=0;i<8;++i)b[p+i]=(uint8_t)(v>>(8*i)); }
static uint32_t align32(uint32_t x,uint32_t a){ return (x+a-1u)&~(a-1u); }
static size_t alignsz(size_t x,size_t a){ return (x+a-1u)&~(a-1u); }
static std::vector<uint8_t> read_file(const fs::path& p){ std::ifstream f(p,std::ios::binary); if(!f)throw std::runtime_error("cannot open "+p.string()); return std::vector<uint8_t>((std::istreambuf_iterator<char>(f)),{}); }
static void write_file(const fs::path& p,const std::vector<uint8_t>& b){ std::ofstream f(p,std::ios::binary|std::ios::trunc); if(!f)throw std::runtime_error("cannot write "+p.string()); f.write((const char*)b.data(),(std::streamsize)b.size()); }
static std::string lower(std::string s){for(char&c:s)c=(char)std::tolower((unsigned char)c);return s;}

struct Reloc { uint32_t off=0,sym=0; uint16_t type=0; };
struct InSection { std::string name; std::vector<uint8_t> data; uint32_t virtual_size=0,chars=0; std::vector<Reloc> relocs; int out_group=-1; uint32_t out_off=0; };
struct Symbol { std::string name; uint32_t value=0; int16_t section=0; uint16_t type=0; uint8_t storage=0,aux=0; bool valid=false,aux_entry=false; };
struct Object { fs::path path; uint16_t machine=0; std::vector<InSection> sections; std::vector<Symbol> symbols; };

static std::string name_from8(const uint8_t* p){ size_t n=0; while(n<8&&p[n])++n; return std::string((const char*)p,n); }
static std::string string_at(const std::vector<uint8_t>& b,size_t strbase,uint32_t off){ if(off<4||strbase+off>=b.size())return ""; size_t p=strbase+off,e=p; while(e<b.size()&&b[e])++e; return std::string((const char*)&b[p],e-p); }
static Object read_coff(const fs::path& path){
    auto b=read_file(path); if(b.size()<20)throw std::runtime_error("not a COFF object: "+path.string());
    Object o;o.path=path;o.machine=r16(b,0);uint16_t nsec=r16(b,2);uint32_t symptr=r32(b,8),nsym=r32(b,12);uint16_t opt=r16(b,16);
    if(o.machine!=0x8664&&o.machine!=0x014c)throw std::runtime_error("unsupported COFF machine in "+path.string());
    size_t sh=20u+opt;if(sh+(size_t)nsec*40u>b.size())throw std::runtime_error("truncated COFF section table");
    size_t strbase=(size_t)symptr+(size_t)nsym*18u;if(strbase+4>b.size())strbase=b.size();
    auto secname=[&](size_t p){std::string s=name_from8(&b[p]);if(!s.empty()&&s[0]=='/'&&s.size()>1){try{return string_at(b,strbase,(uint32_t)std::stoul(s.substr(1)));}catch(...){}}return s;};
    o.sections.resize(nsec);
    for(uint16_t i=0;i<nsec;++i){size_t p=sh+(size_t)i*40u;auto&s=o.sections[i];s.name=secname(p);s.virtual_size=r32(b,p+8);uint32_t rawsz=r32(b,p+16),raw=r32(b,p+20),rp=r32(b,p+24);uint16_t nr=r16(b,p+32);s.chars=r32(b,p+36);if(rawsz){if((size_t)raw+rawsz>b.size())throw std::runtime_error("truncated COFF section data");s.data.assign(b.begin()+raw,b.begin()+raw+rawsz);}if(!s.virtual_size)s.virtual_size=rawsz;if(nr){if((size_t)rp+(size_t)nr*10u>b.size())throw std::runtime_error("truncated COFF relocations");for(uint16_t q=0;q<nr;++q){size_t z=(size_t)rp+(size_t)q*10u;s.relocs.push_back({r32(b,z),r32(b,z+4),r16(b,z+8)});}}}
    o.symbols.resize(nsym);if(nsym&&((size_t)symptr+(size_t)nsym*18u>b.size()))throw std::runtime_error("truncated COFF symbols");
    for(uint32_t i=0;i<nsym;){size_t p=(size_t)symptr+(size_t)i*18u;Symbol s;s.valid=true;uint32_t z=r32(b,p);if(z==0)s.name=string_at(b,strbase,r32(b,p+4));else s.name=name_from8(&b[p]);s.value=r32(b,p+8);s.section=(int16_t)r16(b,p+12);s.type=r16(b,p+14);s.storage=b[p+16];s.aux=b[p+17];o.symbols[i]=s;for(uint8_t a=0;a<s.aux&&i+1+a<nsym;++a)o.symbols[i+1+a].aux_entry=true;i+=1u+s.aux;}
    return o;
}

static bool skip_section(const InSection&s){auto n=lower(s.name);if(s.chars&0x00000800u)return true;if(n==".drectve"||n==".llvm_addrsig"||n.rfind(".debug",0)==0||n==".comment")return true;return false;}
struct OutSection { std::string name;std::vector<uint8_t> data;uint32_t virtual_size=0,rva=0,raw=0,raw_size=0,chars=0; };
static int group_for(const InSection&s){if(s.chars&0x00000020u)return 0;if(s.chars&0x80000000u)return 2;return 1;}
static size_t group_align(int g){return g==0?16u:8u;}

struct ImportDesc {std::string exact,canonical,dll;bool indirect=false;};
static std::string undecorate(std::string n){if(n.rfind("__imp_",0)==0)n=n.substr(6);else if(n.rfind("_imp__",0)==0)n=n.substr(6);if(!n.empty()&&n[0]=='_')n.erase(n.begin());auto at=n.find('@');if(at!=std::string::npos){bool digits=at+1<n.size();for(size_t i=at+1;i<n.size();++i)digits=digits&&std::isdigit((unsigned char)n[i]);if(digits)n=n.substr(0,at);}return n;}
static bool is_indirect_import(const std::string&n){return n.rfind("__imp_",0)==0||n.rfind("_imp__",0)==0;}
static std::string import_dll(const std::string&canon){
    static const std::unordered_set<std::string> crt={"printf","puts","putchar","sprintf","snprintf","malloc","calloc","realloc","free","memcpy","memmove","memset","strlen","strcmp","strncmp","atoi","strtol","exit","abort"};
    static const std::unordered_set<std::string> k32={"ExitProcess","GetStdHandle","WriteFile","ReadFile","Sleep","GetLastError","SetLastError"};
    if(crt.count(canon))return "msvcrt.dll";if(k32.count(canon))return "kernel32.dll";return "";
}

struct DefRef {size_t obj=0;uint32_t sym=0;};
struct LinkState {bool x64=false;uint16_t machine=0;uint64_t image_base=0;std::vector<Object> objs;std::unordered_map<std::string,DefRef> globals;std::vector<OutSection> outs;std::vector<ImportDesc> imports;std::unordered_map<std::string,size_t> import_by_canon;std::unordered_map<std::string,uint32_t> import_target;std::unordered_map<std::string,uint32_t> iat_target;};
static uint32_t symbol_rva(LinkState& st,size_t oi,const Symbol&s){if(s.section<=0||(size_t)s.section>st.objs[oi].sections.size())throw std::runtime_error("symbol has no section: "+s.name);auto&sec=st.objs[oi].sections[(size_t)s.section-1];if(sec.out_group<0)throw std::runtime_error("symbol points to discarded section: "+s.name);return st.outs[(size_t)sec.out_group].rva+sec.out_off+s.value;}
static uint32_t resolve_symbol(LinkState&st,size_t oi,uint32_t si){if(si>=st.objs[oi].symbols.size())throw std::runtime_error("bad relocation symbol index");auto&s=st.objs[oi].symbols[si];if(!s.valid||s.aux_entry)throw std::runtime_error("relocation references invalid symbol");if(s.section>0)return symbol_rva(st,oi,s);if(s.section==-1)return s.value;auto it=st.globals.find(s.name);if(it!=st.globals.end())return symbol_rva(st,it->second.obj,st.objs[it->second.obj].symbols[it->second.sym]);auto ii=st.import_target.find(s.name);if(ii!=st.import_target.end())return ii->second;auto ia=st.iat_target.find(s.name);if(ia!=st.iat_target.end())return ia->second;throw std::runtime_error("unresolved external symbol: "+s.name);}
static void collect_imports(LinkState&st){std::set<std::string> unresolved;for(size_t oi=0;oi<st.objs.size();++oi)for(auto&sec:st.objs[oi].sections)if(sec.out_group>=0)for(auto&r:sec.relocs){if(r.sym>=st.objs[oi].symbols.size())continue;auto&s=st.objs[oi].symbols[r.sym];if(s.valid&&!s.aux_entry&&s.section==0&&!st.globals.count(s.name))unresolved.insert(s.name);}unresolved.insert(st.x64?"ExitProcess":"_ExitProcess@4");for(auto&exact:unresolved){std::string canon=undecorate(exact),dll=import_dll(canon);if(dll.empty())continue;auto it=st.import_by_canon.find(canon);if(it==st.import_by_canon.end()){st.import_by_canon[canon]=st.imports.size();st.imports.push_back({exact,canon,dll,is_indirect_import(exact)});}}}

struct IdataBuild{std::vector<uint8_t> bytes;};
static IdataBuild build_idata(const std::vector<ImportDesc>& imports,bool x64){IdataBuild z;std::map<std::string,std::vector<size_t>> groups;for(size_t i=0;i<imports.size();++i)groups[imports[i].dll].push_back(i);size_t desc_count=groups.size()+1;z.bytes.resize(desc_count*20u,0);size_t ptr=x64?8:4;for(auto&kv:groups){z.bytes.resize(alignsz(z.bytes.size(),ptr),0);z.bytes.resize(z.bytes.size()+(kv.second.size()+1)*ptr,0);z.bytes.resize(z.bytes.size()+(kv.second.size()+1)*ptr,0);}for(auto&i:imports){z.bytes.resize(alignsz(z.bytes.size(),2),0);w16(z.bytes,0);z.bytes.insert(z.bytes.end(),i.canonical.begin(),i.canonical.end());z.bytes.push_back(0);}for(auto&kv:groups){z.bytes.insert(z.bytes.end(),kv.first.begin(),kv.first.end());z.bytes.push_back(0);}return z;}
static void add_entry_and_thunks(LinkState&st,uint32_t&entry_off,std::unordered_map<std::string,uint32_t>&thunk_off,size_t&entry_main_patch,size_t&entry_exit_patch){auto&text=st.outs[0].data;text.resize(alignsz(text.size(),16),0x90);entry_off=(uint32_t)text.size();if(st.x64){text.insert(text.end(),{0x48,0x83,0xec,0x28,0xe8,0,0,0,0,0x89,0xc1,0xe8,0,0,0,0,0xcc});entry_main_patch=entry_off+5;entry_exit_patch=entry_off+12;}else{text.insert(text.end(),{0xe8,0,0,0,0,0x50,0xe8,0,0,0,0,0xcc});entry_main_patch=entry_off+1;entry_exit_patch=entry_off+7;}for(auto&i:st.imports){if(thunk_off.count(i.canonical))continue;text.resize(alignsz(text.size(),st.x64?8:4),0x90);uint32_t off=(uint32_t)text.size();thunk_off[i.canonical]=off;text.insert(text.end(),{0xff,0x25,0,0,0,0});}st.outs[0].virtual_size=(uint32_t)text.size();}
static uint32_t find_global_rva(LinkState&st,const std::vector<std::string>&names){for(auto&n:names){auto it=st.globals.find(n);if(it!=st.globals.end())return symbol_rva(st,it->second.obj,st.objs[it->second.obj].symbols[it->second.sym]);}throw std::runtime_error("entry symbol not found (expected main)");}
static void patch_rel32(std::vector<uint8_t>&data,size_t off,uint32_t place_rva,uint32_t target_rva,int extra=0){int32_t add=(int32_t)r32(data,off);int64_t v=(int64_t)add+(int64_t)target_rva-(int64_t)(place_rva+4u+(uint32_t)extra);if(v<INT32_MIN||v>INT32_MAX)throw std::runtime_error("REL32 out of range");p32(data,off,(uint32_t)(int32_t)v);}

static int link_pe(const std::vector<std::string>&inputs,const std::string&output,const std::string&target){
    if(inputs.empty())throw std::runtime_error("no object inputs");LinkState st;st.x64=target=="windows-x86_64";if(!st.x64&&target!="windows-x86")throw std::runtime_error("jauld supports windows-x86_64/windows-x86");st.machine=st.x64?0x8664:0x014c;st.image_base=st.x64?0x140000000ull:0x00400000ull;
    for(auto&p:inputs){auto o=read_coff(p);if(o.machine!=st.machine)throw std::runtime_error("object architecture mismatch: "+p);st.objs.push_back(std::move(o));}
    st.outs={{".text",{},0,0,0,0,0x60000020u},{".rdata",{},0,0,0,0,0x40000040u},{".data",{},0,0,0,0,0xC0000040u},{".idata",{},0,0,0,0,0xC0000040u}};
    for(size_t oi=0;oi<st.objs.size();++oi){auto&o=st.objs[oi];for(auto&s:o.sections){if(skip_section(s))continue;int g=group_for(s);s.out_group=g;auto&out=st.outs[(size_t)g];out.data.resize(alignsz(out.data.size(),group_align(g)),0);s.out_off=(uint32_t)out.data.size();out.data.insert(out.data.end(),s.data.begin(),s.data.end());uint32_t need=s.out_off+std::max<uint32_t>((uint32_t)s.data.size(),s.virtual_size);if(need>out.data.size())out.data.resize(need,0);out.virtual_size=(uint32_t)out.data.size();}}
    for(size_t oi=0;oi<st.objs.size();++oi){auto&o=st.objs[oi];for(uint32_t si=0;si<o.symbols.size();++si){auto&s=o.symbols[si];if(!s.valid||s.aux_entry||s.section<=0||s.storage!=2||s.name.empty())continue;if((size_t)s.section>o.sections.size()||o.sections[(size_t)s.section-1].out_group<0)continue;if(st.globals.count(s.name))throw std::runtime_error("duplicate external symbol: "+s.name);st.globals[s.name]={oi,si};}}
    collect_imports(st);std::unordered_map<std::string,uint32_t>thunk_off;uint32_t entry_off=0;size_t main_patch=0,exit_patch=0;add_entry_and_thunks(st,entry_off,thunk_off,main_patch,exit_patch);auto id=build_idata(st.imports,st.x64);st.outs[3].data=id.bytes;st.outs[3].virtual_size=(uint32_t)id.bytes.size();
    const uint32_t sec_align=0x1000,file_align=0x200;uint16_t nsec=4;uint16_t optsz=st.x64?0xF0:0xE0;uint32_t headers=align32(0x80+4+20+optsz+nsec*40u,file_align),rva=sec_align,raw=headers;for(auto&out:st.outs){out.rva=rva;out.raw=raw;out.raw_size=align32((uint32_t)out.data.size(),file_align);rva=align32(rva+std::max<uint32_t>(1,out.virtual_size),sec_align);raw+=out.raw_size;}uint32_t size_image=align32(rva,sec_align);
    auto&idata=st.outs[3].data;std::map<std::string,std::vector<size_t>>groups;for(size_t i=0;i<st.imports.size();++i)groups[st.imports[i].dll].push_back(i);size_t ptr=st.x64?8:4;size_t descbytes=(groups.size()+1)*20u;size_t cur=alignsz(descbytes,ptr);struct GG{std::string dll;std::vector<size_t> idx;uint32_t int_off,iat_off,dll_off;};std::vector<GG>gg;for(auto&kv:groups){GG g{kv.first,kv.second,(uint32_t)cur,0,0};cur+=(kv.second.size()+1)*ptr;g.iat_off=(uint32_t)cur;cur+=(kv.second.size()+1)*ptr;gg.push_back(g);}std::vector<uint32_t>hint(st.imports.size());for(size_t i=0;i<st.imports.size();++i){cur=alignsz(cur,2);hint[i]=(uint32_t)cur;cur+=2+st.imports[i].canonical.size()+1;}for(auto&g:gg){g.dll_off=(uint32_t)cur;cur+=g.dll.size()+1;}
    size_t di=0;for(auto&g:gg){size_t d=di++*20u;p32(idata,d,st.outs[3].rva+g.int_off);p32(idata,d+12,st.outs[3].rva+g.dll_off);p32(idata,d+16,st.outs[3].rva+g.iat_off);for(size_t k=0;k<g.idx.size();++k){size_t idx=g.idx[k];uint64_t hr=st.outs[3].rva+hint[idx];uint32_t io=g.int_off+(uint32_t)(k*ptr),ao=g.iat_off+(uint32_t)(k*ptr);if(st.x64){p64(idata,io,hr);p64(idata,ao,hr);}else{p32(idata,io,(uint32_t)hr);p32(idata,ao,(uint32_t)hr);}uint32_t iat=st.outs[3].rva+ao;auto canon=st.imports[idx].canonical;st.iat_target["__imp_"+canon]=iat;st.iat_target["_imp__"+canon]=iat;}}
    for(auto&i:st.imports){uint32_t toff=thunk_off.at(i.canonical),trva=st.outs[0].rva+toff;uint32_t iat=0;for(auto&g:gg)for(size_t k=0;k<g.idx.size();++k)if(st.imports[g.idx[k]].canonical==i.canonical)iat=st.outs[3].rva+g.iat_off+(uint32_t)(k*ptr);if(!iat)throw std::runtime_error("internal import layout error");if(st.x64){int64_t d=(int64_t)iat-(int64_t)(trva+6);p32(st.outs[0].data,toff+2,(uint32_t)(int32_t)d);}else p32(st.outs[0].data,toff+2,(uint32_t)(st.image_base+iat));st.import_target[i.exact]=i.indirect?iat:trva;st.import_target[i.canonical]=trva;st.import_target["_"+i.canonical]=trva;st.import_target["_"+i.canonical+"@4"]=trva;st.import_target["_ExitProcess@4"]=thunk_off.count("ExitProcess")?st.outs[0].rva+thunk_off["ExitProcess"]:trva;st.iat_target["__imp_"+i.canonical]=iat;st.iat_target["_imp__"+i.canonical]=iat;}
    uint32_t mainr=find_global_rva(st,st.x64?std::vector<std::string>{"main"}:std::vector<std::string>{"_main","main"});uint32_t entryr=st.outs[0].rva+entry_off;patch_rel32(st.outs[0].data,main_patch,st.outs[0].rva+(uint32_t)main_patch,mainr);uint32_t exitr=st.import_target.count("ExitProcess")?st.import_target["ExitProcess"]:st.import_target["_ExitProcess@4"];patch_rel32(st.outs[0].data,exit_patch,st.outs[0].rva+(uint32_t)exit_patch,exitr);
    for(size_t oi=0;oi<st.objs.size();++oi){auto&o=st.objs[oi];for(auto&sec:o.sections){if(sec.out_group<0)continue;auto&dst=st.outs[(size_t)sec.out_group].data;for(auto&rel:sec.relocs){size_t po=(size_t)sec.out_off+rel.off;if(po+4>dst.size())throw std::runtime_error("relocation outside section in "+o.path.string());uint32_t place=st.outs[(size_t)sec.out_group].rva+(uint32_t)po;uint32_t targetr=resolve_symbol(st,oi,rel.sym);if(st.x64){if(rel.type>=0x0004&&rel.type<=0x0009)patch_rel32(dst,po,place,targetr,(int)rel.type-4);else if(rel.type==0x0001){uint64_t add=r64(dst,po);p64(dst,po,add+st.image_base+targetr);}else if(rel.type==0x0002){uint32_t add=r32(dst,po);p32(dst,po,add+(uint32_t)(st.image_base+targetr));}else if(rel.type==0x0003){uint32_t add=r32(dst,po);p32(dst,po,add+targetr);}else throw std::runtime_error("unsupported AMD64 relocation type "+std::to_string(rel.type)+" in "+o.path.string());}else{if(rel.type==0x0014)patch_rel32(dst,po,place,targetr);else if(rel.type==0x0006){uint32_t add=r32(dst,po);p32(dst,po,add+(uint32_t)(st.image_base+targetr));}else if(rel.type==0x0007){uint32_t add=r32(dst,po);p32(dst,po,add+targetr);}else throw std::runtime_error("unsupported i386 relocation type "+std::to_string(rel.type)+" in "+o.path.string());}}}}
    std::vector<uint8_t> pe(headers,0);pe[0]='M';pe[1]='Z';p32(pe,0x3c,0x80);size_t p=0x80;pe[p++]='P';pe[p++]='E';pe[p++]=0;pe[p++]=0;p16(pe,p,st.machine);p+=2;p16(pe,p,nsec);p+=2;p32(pe,p,0);p+=4;p32(pe,p,0);p+=4;p32(pe,p,0);p+=4;p16(pe,p,optsz);p+=2;p16(pe,p,(uint16_t)(0x0002|(st.x64?0x0020:0x0100)));p+=2;size_t optp=p;p16(pe,p,st.x64?0x20b:0x10b);p+=2;pe[p++]=1;pe[p++]=0;p32(pe,p,st.outs[0].raw_size);p+=4;p32(pe,p,st.outs[1].raw_size+st.outs[2].raw_size+st.outs[3].raw_size);p+=4;p32(pe,p,0);p+=4;p32(pe,p,entryr);p+=4;p32(pe,p,st.outs[0].rva);p+=4;if(!st.x64){p32(pe,p,st.outs[2].rva);p+=4;p32(pe,p,(uint32_t)st.image_base);p+=4;}else{p64(pe,p,st.image_base);p+=8;}p32(pe,p,sec_align);p+=4;p32(pe,p,file_align);p+=4;p16(pe,p,6);p+=2;p16(pe,p,0);p+=2;p16(pe,p,0);p+=2;p16(pe,p,0);p+=2;p16(pe,p,6);p+=2;p16(pe,p,0);p+=2;p32(pe,p,0);p+=4;p32(pe,p,size_image);p+=4;p32(pe,p,headers);p+=4;p32(pe,p,0);p+=4;p16(pe,p,3);p+=2;p16(pe,p,0x8100);p+=2;if(st.x64){p64(pe,p,1ull<<20);p+=8;p64(pe,p,0x1000);p+=8;p64(pe,p,1ull<<20);p+=8;p64(pe,p,0x1000);p+=8;}else{p32(pe,p,1u<<20);p+=4;p32(pe,p,0x1000);p+=4;p32(pe,p,1u<<20);p+=4;p32(pe,p,0x1000);p+=4;}p32(pe,p,0);p+=4;p32(pe,p,16);p+=4;size_t dirs=p;for(int i=0;i<16;++i){p32(pe,p,0);p+=4;p32(pe,p,0);p+=4;}p32(pe,dirs+8,st.outs[3].rva);p32(pe,dirs+12,(uint32_t)(groups.size()*20u));uint32_t iatmin=0xffffffffu,iatmax=0;for(auto&g:gg){iatmin=std::min(iatmin,st.outs[3].rva+g.iat_off);iatmax=std::max(iatmax,st.outs[3].rva+g.iat_off+(uint32_t)((g.idx.size()+1)*ptr));}if(iatmin!=0xffffffffu){p32(pe,dirs+12*8,iatmin);p32(pe,dirs+12*8+4,iatmax-iatmin);}if(p-optp!=optsz)throw std::runtime_error("internal optional header size mismatch");
    auto putsec=[&](size_t hp,const OutSection&s){for(size_t i=0;i<8;++i)pe[hp+i]=(uint8_t)(i<s.name.size()?s.name[i]:0);p32(pe,hp+8,s.virtual_size);p32(pe,hp+12,s.rva);p32(pe,hp+16,s.raw_size);p32(pe,hp+20,s.raw);p32(pe,hp+24,0);p32(pe,hp+28,0);p16(pe,hp+32,0);p16(pe,hp+34,0);p32(pe,hp+36,s.chars);};size_t shp=0x80+4+20+optsz;for(size_t i=0;i<st.outs.size();++i)putsec(shp+i*40u,st.outs[i]);
    std::vector<uint8_t> out=pe;for(auto&s:st.outs){if(out.size()<s.raw)out.resize(s.raw,0);out.insert(out.end(),s.data.begin(),s.data.end());out.resize(s.raw+s.raw_size,0);}write_file(output,out);std::cout<<"jauld: wrote "<<output<<" ("<<(st.x64?"PE32+ x86-64":"PE32 x86")<<", internal linker, "<<out.size()<<" bytes)\n";return 0;
}

static void usage(){std::cout<<"jauld 0.1\nusage: jauld <input.obj> [more.obj ...] -o <program.exe> --target <windows-x86_64|windows-x86>\n";}
int main(int argc,char**argv){try{if(argc<2){usage();return 0;}std::vector<std::string>in;std::string out="a.exe",target;for(int i=1;i<argc;++i){std::string a=argv[i];if(a=="-o"&&i+1<argc)out=argv[++i];else if(a=="--target"&&i+1<argc)target=argv[++i];else if(a=="--help"||a=="-h"){usage();return 0;}else in.push_back(a);}if(target.empty()){auto o=read_coff(in.at(0));target=o.machine==0x8664?"windows-x86_64":"windows-x86";}return link_pe(in,out,target);}catch(const std::exception&e){std::cerr<<"jauld: "<<e.what()<<"\n";return 1;}}
